//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class EmployeeDirectory
{
    /// <summary>
    /// pnlError control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Panel pnlError;

    /// <summary>
    /// txtSearch control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtSearch;

    /// <summary>
    /// btnSearch control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnSearch;

    /// <summary>
    /// btnClear control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnClear;

    /// <summary>
    /// gvEmployees control.
    /// </summary>
    protected global::System.Web.UI.WebControls.GridView gvEmployees;
}
